ERROR   2022-06-22 10:01:47,343  D:\work_code\pytest-auto-api2\logs\error.log:assertControl.py:135 JsonPath值获取失败$.errorCode
ERROR   2022-06-22 10:03:39,465  D:\work_code\pytest-auto-api2\logs\error.log:assertControl.py:135 JsonPath值获取失败$.errorCode
ERROR   2022-06-22 11:08:12,108  D:\work_code\pytest-auto-api2\logs\error.log:mysqlControl.py:40 数据库连接失败，失败原因object supporting the buffer API required
ERROR   2022-06-22 11:08:12,112  D:\work_code\pytest-auto-api2\logs\error.log:mysqlControl.py:71 数据库连接失败，失败原因'GenerateCaseDate' object has no attribute 'cur'
ERROR   2022-06-22 11:08:12,113  D:\work_code\pytest-auto-api2\logs\error.log:mysqlControl.py:49 数据库连接失败，失败原因'GenerateCaseDate' object has no attribute 'cur'
ERROR   2022-06-22 11:08:40,761  D:\work_code\pytest-auto-api2\logs\error.log:mysqlControl.py:40 数据库连接失败，失败原因object supporting the buffer API required
ERROR   2022-06-22 11:08:40,779  D:\work_code\pytest-auto-api2\logs\error.log:mysqlControl.py:49 数据库连接失败，失败原因'GenerateCaseDate' object has no attribute 'cur'
ERROR   2022-06-22 11:08:56,066  D:\work_code\pytest-auto-api2\logs\error.log:mysqlControl.py:40 数据库连接失败，失败原因object supporting the buffer API required
ERROR   2022-06-22 11:08:56,162  D:\work_code\pytest-auto-api2\logs\error.log:mysqlControl.py:40 数据库连接失败，失败原因object supporting the buffer API required
ERROR   2022-06-22 11:08:56,162  D:\work_code\pytest-auto-api2\logs\error.log:mysqlControl.py:71 数据库连接失败，失败原因'MysqlDB' object has no attribute 'cur'
ERROR   2022-06-22 11:08:56,163  D:\work_code\pytest-auto-api2\logs\error.log:mysqlControl.py:49 数据库连接失败，失败原因'MysqlDB' object has no attribute 'cur'
ERROR   2022-06-22 11:08:56,163  D:\work_code\pytest-auto-api2\logs\error.log:mysqlControl.py:49 数据库连接失败，失败原因'GenerateCaseDate' object has no attribute 'cur'
ERROR   2022-06-22 11:09:11,556  D:\work_code\pytest-auto-api2\logs\error.log:mysqlControl.py:40 数据库连接失败，失败原因object supporting the buffer API required
ERROR   2022-06-22 11:09:11,652  D:\work_code\pytest-auto-api2\logs\error.log:mysqlControl.py:40 数据库连接失败，失败原因object supporting the buffer API required
ERROR   2022-06-22 11:09:11,654  D:\work_code\pytest-auto-api2\logs\error.log:mysqlControl.py:71 数据库连接失败，失败原因'MysqlDB' object has no attribute 'cur'
ERROR   2022-06-22 11:09:11,655  D:\work_code\pytest-auto-api2\logs\error.log:mysqlControl.py:49 数据库连接失败，失败原因'MysqlDB' object has no attribute 'cur'
ERROR   2022-06-22 11:09:11,656  D:\work_code\pytest-auto-api2\logs\error.log:mysqlControl.py:49 数据库连接失败，失败原因'GenerateCaseDate' object has no attribute 'cur'
ERROR   2022-06-22 11:09:44,679  D:\work_code\pytest-auto-api2\logs\error.log:mysqlControl.py:40 数据库连接失败，失败原因object supporting the buffer API required
ERROR   2022-06-22 11:09:44,681  D:\work_code\pytest-auto-api2\logs\error.log:mysqlControl.py:71 数据库连接失败，失败原因'MysqlDB' object has no attribute 'cur'
ERROR   2022-06-22 11:09:44,682  D:\work_code\pytest-auto-api2\logs\error.log:mysqlControl.py:49 数据库连接失败，失败原因'MysqlDB' object has no attribute 'cur'
